# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.CharField(default=apps.content.models._ent_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=16)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('current_published_version_id', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_created', to='identity.user')),
            ],
            options={
                'db_table': 'content_entries',
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.CharField(default=apps.content.models._ver_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('state', models.CharField(default='draft', max_length=16)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_key', models.CharField(blank=True, max_length=40, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contententry')),
                ('operator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to='identity.user')),
            ],
            options={
                'db_table': 'content_versions',
                'constraints': [models.UniqueConstraint(fields=('published_key',), name='uniq_single_published_per_entry')],
            },
        ),
    ]
