# Generated by Django 5.2.6 on 2026-04-16 09:56

import apps.platform_common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='body',
            field=apps.platform_common.fields.EncryptedTextField(),
        ),
    ]
