# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.tickets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillRun',
            fields=[
                ('id', models.CharField(default=apps.tickets.models._bfr_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('input_fingerprint', models.CharField(max_length=128)),
                ('affected_record_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backfill_runs', to='identity.user')),
            ],
            options={
                'db_table': 'backfill_runs',
            },
        ),
        migrations.CreateModel(
            name='BackfillReinspection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.inspectionrun')),
                ('backfill_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinspections', to='tickets.backfillrun')),
            ],
            options={
                'db_table': 'backfill_reinspections',
            },
        ),
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.CharField(default=apps.tickets.models._tkt_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(default='open', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('severity_snapshot', models.CharField(blank=True, default='', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='catalog.dataset')),
                ('inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.inspectionrun')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tickets', to='identity.user')),
                ('rule_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.inspectionruleresult')),
            ],
            options={
                'db_table': 'issue_tickets',
            },
        ),
        migrations.AddField(
            model_name='backfillrun',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfills', to='tickets.issueticket'),
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.CharField(default=apps.tickets.models._rem_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_actions', to='tickets.issueticket')),
            ],
            options={
                'db_table': 'remediation_actions',
            },
        ),
        migrations.CreateModel(
            name='TicketTransition',
            fields=[
                ('id', models.CharField(default=apps.tickets.models._ttr_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('transitioned_by', models.CharField(max_length=40)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tickets.issueticket')),
            ],
            options={
                'db_table': 'ticket_transitions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='backfillrun',
            unique_together={('ticket', 'input_fingerprint')},
        ),
    ]
