# Generated by Django 5.2.6 on 2026-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=128)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='platform_co_expires_47e527_idx')],
                'unique_together': {('key', 'actor_user_id', 'method', 'path')},
            },
        ),
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=16)),
                ('bucket_key', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='platform_co_window__440e42_idx')],
                'unique_together': {('scope', 'bucket_key', 'window_start')},
            },
        ),
    ]
