# Generated by Django 5.2.6 on 2026-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupScheduleState',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('cron_expr', models.CharField(default='0 1 * * *', max_length=64)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_run_label', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'backup_schedule_state',
            },
        ),
    ]
