# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.audit_monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditExportJob',
            fields=[
                ('id', models.CharField(default=apps.audit_monitoring.models._auex_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(max_length=40)),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('record_count', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_export_jobs',
            },
        ),
        migrations.CreateModel(
            name='MetricRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metric_name', models.CharField(max_length=64)),
                ('metric_value', models.FloatField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metric_rollups',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=apps.audit_monitoring.models._aud_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('payload_before', models.JSONField(blank=True, default=dict)),
                ('payload_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['actor_user_id', 'created_at'], name='audit_logs_actor_u_b024de_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('event_ts', models.DateTimeField(auto_now_add=True)),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('dataset_id', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'event_logs',
                'indexes': [models.Index(fields=['event_type', 'event_ts'], name='event_logs_event_t_de456e_idx')],
            },
        ),
    ]
