# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(default=apps.catalog.models._ds_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('approval_state', models.CharField(default='draft', max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.CharField(default=apps.catalog.models._dmd_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=128)),
                ('retention_class', models.CharField(max_length=64)),
                ('sensitivity_level', models.CharField(max_length=16)),
                ('updated_by', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='catalog.dataset')),
            ],
            options={
                'db_table': 'dataset_metadata',
            },
        ),
        migrations.CreateModel(
            name='DatasetField',
            fields=[
                ('id', models.CharField(default=apps.catalog.models._fld_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(default='string', max_length=16)),
                ('is_queryable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.dataset')),
            ],
            options={
                'db_table': 'dataset_fields',
                'unique_together': {('dataset', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.dataset')),
            ],
            options={
                'db_table': 'dataset_rows',
                'indexes': [models.Index(fields=['dataset', 'id'], name='dataset_row_dataset_827784_idx')],
            },
        ),
    ]
