# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.CharField(default=apps.analytics.models._rpt_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('filter_schema', models.JSONField(blank=True, default=dict)),
                ('time_window_schema', models.JSONField(blank=True, default=dict)),
                ('permission_scope', models.JSONField(blank=True, default=dict)),
                ('query_plan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.user')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to='catalog.dataset')),
            ],
            options={
                'db_table': 'report_definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.CharField(default=apps.analytics.models._rrn_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('resolved_filters', models.JSONField(blank=True, default=dict)),
                ('resolved_time_window', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='complete', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rows_snapshot', models.JSONField(blank=True, default=list)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analytics.reportdefinition')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.user')),
            ],
            options={
                'db_table': 'report_runs',
            },
        ),
    ]
