# Generated by Django 5.2.13 on 2026-04-15 15:37

import apps.analytics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.CharField(default=apps.analytics.models._rsd_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('cron_expr', models.CharField(default='0 3 * * *', max_length=64)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules_created', to='identity.user')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='analytics.reportdefinition')),
            ],
            options={
                'db_table': 'report_schedules',
                'indexes': [models.Index(fields=['active', 'next_run_at'], name='report_sche_active_9392bf_idx')],
            },
        ),
    ]
