# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.identity.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=apps.identity.models._new_role_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=apps.identity.models._new_user_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.CharField(default=apps.identity.models._new_grant_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('principal_type', models.CharField(max_length=16)),
                ('principal_id', models.CharField(max_length=40)),
                ('capability', models.CharField(max_length=128)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permission_grants',
                'indexes': [models.Index(fields=['principal_type', 'principal_id'], name='permission__princip_80cb5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=apps.identity.models._new_session_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='identity.user')),
            ],
            options={
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['expires_at'], name='sessions_expires_bbb852_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='identity.user')),
            ],
            options={
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
