# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.quality.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRun',
            fields=[
                ('id', models.CharField(default=apps.quality.models._ins_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('trigger_mode', models.CharField(default='manual', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('gate_pass', models.BooleanField(default=False)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=40)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='catalog.dataset')),
            ],
            options={
                'db_table': 'inspection_runs',
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.CharField(default=apps.quality.models._isd_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('cron_expr', models.CharField(default='0 2 * * *', max_length=64)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='catalog.dataset')),
            ],
            options={
                'db_table': 'inspection_schedules',
            },
        ),
        migrations.CreateModel(
            name='QualityRule',
            fields=[
                ('id', models.CharField(default=apps.quality.models._qrl_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=4)),
                ('threshold_value', models.FloatField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='catalog.dataset')),
            ],
            options={
                'db_table': 'quality_rules',
            },
        ),
        migrations.CreateModel(
            name='InspectionRuleResult',
            fields=[
                ('id', models.CharField(default=apps.quality.models._irr_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('measured_value', models.FloatField()),
                ('threshold_snapshot', models.FloatField()),
                ('severity_snapshot', models.CharField(max_length=4)),
                ('weight_snapshot', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('breach_delta', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.inspectionrun')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.qualityrule')),
            ],
            options={
                'db_table': 'inspection_rule_results',
            },
        ),
        migrations.CreateModel(
            name='QualityRuleField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_attachments', to='catalog.datasetfield')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_fields', to='quality.qualityrule')),
            ],
            options={
                'db_table': 'quality_rule_fields',
                'unique_together': {('rule', 'field')},
            },
        ),
    ]
