# Generated by Django 5.2.13 on 2026-04-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionschedule',
            name='last_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='inspectionschedule',
            index=models.Index(fields=['active', 'next_run_at'], name='inspection__active_12ab7d_idx'),
        ),
    ]
