# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.exports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.CharField(default=apps.exports.models._exp_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=8)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analytics.reportrun')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.user')),
            ],
            options={
                'db_table': 'export_jobs',
            },
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.CharField(default=apps.exports.models._exf_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('part_number', models.IntegerField()),
                ('row_count', models.IntegerField()),
                ('path', models.CharField(max_length=1024)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exports.exportjob')),
            ],
            options={
                'db_table': 'export_files',
                'unique_together': {('export_job', 'part_number')},
            },
        ),
    ]
