# Generated by Django 5.2.6 on 2026-04-15 11:17

import apps.lineage.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.CharField(default=apps.lineage.models._led_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downstream_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_edges', to='catalog.dataset')),
                ('upstream_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_edges', to='catalog.dataset')),
            ],
            options={
                'db_table': 'lineage_edges',
                'indexes': [models.Index(fields=['upstream_dataset', 'recorded_at'], name='lineage_edg_upstrea_02df32_idx'), models.Index(fields=['downstream_dataset', 'recorded_at'], name='lineage_edg_downstr_046a6c_idx')],
            },
        ),
    ]
